# Run unittests

name: test

# Allow to trigger the workflow manually (e.g. when pushing changes to `etils`)
on: [push, workflow_dispatch]

# Cancel in-progress runs for the current workflow if not on the main branch
# (as it mark the unittests as failed).
# Conditionals to concurrent are based on the solution proposed in this link:
# https://github.community/t/concurrency-cancel-in-progress-but-not-when-ref-is-master/194707
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  # Cancel only PR intermediate builds
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    # Install deps
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Get current date.
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=today::$(date +'%Y-%m-%d')"

    # The cache is refreshed everyday.
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: >-
            ${{ env.pythonLocation }}
            ${{ hashFiles('setup.py') }}
            ${{ hashFiles('requirements.txt') }}
            ${{ hashFiles('requirements-dev.txt') }}
            ${{ hashFiles('jax3d/projects/nesf/requirements.txt') }}
            ${{ steps.date.outputs.today }}

    - run: pip --version
    # TODO(epot): Restore once https://github.com/pypa/pip/issues/10910 is fixed (`-` vs `_`).
    - run: pip uninstall -y etils
    - run: pip install -e .[dev]  # Install dev requirements
    - run: pip install -e .[nesf] # Install nesf requirements

    - name: Run core tests
      # Args:
      # -vv: Verbose logs
      # -n auto: Parallelize tests in processes
      # --durations=X: Log the X longest tests
      run: |
        pytest -vv -n auto \
          --durations=10
